name: Deploy to EC2 with rsync

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
            echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem && chmod 400 ec2_key.pem
            

      - name: test SSH Connection
        run:  ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_HOST }} "echo 'SSH connection successful'"

      - name: Rsync files to EC2
        run: |
          rsync -avz -e "ssh -i ec2_key.pem -o StrictHostKeyChecking=no" ./ ${{ secrets.EC2_HOST }}:/home/ubuntu/app --exclude '.git'
      - name: Restart app on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/app
            docker compose down
            docker compose up -d --build
          EOF